# -*- coding: utf-8 -*-
"""VGG_16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2uob4a_KoOG8x2OhR8fVMXuoT77mhLE
"""

!pip install tensorflow pillow matplotlib

import tensorflow as tf
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input, decode_predictions
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import io

from google.colab import files
uploaded = files.upload()
img_path = list(uploaded.keys())[0]

img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)

model = VGG16(weights='imagenet')


preds = model.predict(img_array)
decoded_preds = decode_predictions(preds, top=3)[0]

print("Top predictions:")
for i, (imagenet_id, label, confidence) in enumerate(decoded_preds):
    print(f"{i+1}. {label} ({confidence * 100:.2f}%)")

plt.imshow(img)
plt.axis('off')
plt.title("Uploaded Image")
plt.show()